### ISSUE TITLE
Issue Xcode 11 while create release build 

### ISSUE THREAD

**Issue by sumeet85** [lisen87/image_pickers#10]
error: Unexpected duplicate tasks:
    1) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/left_arrow.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow.png'
    2) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/left_arrow.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow.png'
    error: Unexpected duplicate tasks:
    1) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/error.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/error.png'
    2) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/error.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/error.png'
    error: Unexpected duplicate tasks:
    1) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/right_arrow@2x.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow@2x.png'
    2) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/right_arrow@2x.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow@2x.png'
    error: Unexpected duplicate tasks:
    1) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/left_arrow@2x.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow@2x.png'
    2) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/left_arrow@2x.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow@2x.png'
    error: Unexpected duplicate tasks:
    1) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/right_arrow.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow.png'
    2) Target 'image_pickers' (project 'Pods') has copy command from '/Users/mituser/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7/ios/Classes/AKGallery/img/right_arrow.png' to '/Users/mituser/Documents/Soft/SF/Sanapp/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow.png'
    note: Using new build system
    note: Planning build
    note: Constructing build description

**Comment by cuixiaocun** [comment]
File -> workspace settings，choose  “Legacy Build System"--->build

**Comment by sumeet85** [comment]
Not worked 

After File -> workspace settings，choose “Legacy Build System"--->build

 BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET ZLPhotoBrowser OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/mituser/Downloads/image_pickers-master 2/example/ios/Pods/ZLPhotoBrowser/ZLPhotoBrowser/PhotoBrowser/ZLPhotoActionSheet.m:557:124: warning: values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead [-Wformat]
            [self.btnCancel setTitle:[NSString stringWithFormat:@"%@(%ld)", GetLocalLanguageTextValue(ZLPhotoBrowserDoneText), self.arrSelectedModels.count] forState:UIControlStateNormal];
                                                                     ~~~                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     %lu                                                       (unsigned long)
    1 warning generated.
    /Users/mituser/Downloads/image_pickers-master 2/example/ios/Pods/Z

**Comment by sumeet85** [comment]
any one please help

**Comment by cuixiaocun** [comment]
Please send me the whole project code you have made a mistake 。
1597828092@qq.com

**Comment by cuixiaocun** [comment]
> any one please help

Please send me the whole project code you have made a mistake 。
1597828092@qq.com

**Comment by sumeet85** [comment]
I Fixed the issue removed ios Extension target

**Comment by OMOBruce** [comment]
> I Fixed the issue removed ios Extension target
how to removed ios Extension target?

**Comment by OMOBruce** [comment]
> I Fixed the issue removed ios Extension target

how to removed ios Extension target?

**Comment by harloom** [comment]
> I Fixed the issue removed ios Extension target

how removed iOS extension target?

**Comment by Faisalkc4u** [comment]
how to remove the iOS extension target?

**Comment by Faisalkc4u** [comment]
It's about New Build System, change your ios workspace to Legacy Build System

![Screen Shot 2020-03-04 at 10 44 41 AM](https://user-images.githubusercontent.com/12441355/75852641-e51dbc00-5e05-11ea-9cc8-e2f80e99a271.png)

**Comment by LDXu** [comment]
how to removed ios Extension target?

**Comment by LDXu** [comment]
@sumeet85

**Comment by LDXu** [comment]
@OMOBruce ok?

**Comment by OMOBruce** [comment]
> @OMOBruce ok?

我直接把AKGallery库的资源文件删了。更换xcode的编译模式似乎是没有用的。

**Comment by LDXu** [comment]
确实是资源图片的问题，这个我修正了

**Comment by gityan** [comment]
> > @OMOBruce ok?
> 
> 我直接把AKGallery库的资源文件删了。更换xcode的编译模式似乎是没有用的。

直接删除img文件夹么，但是还是会报错，找不到文件啊，Build input file cannot be found.

**Comment by gityan** [comment]
> 确实是资源图片的问题，这个我修正了

具体是怎么解决的呢？
