### ISSUE TITLE
Ios can't build after upgrade to 2.0.0+6 

### ISSUE THREAD

**Issue by niypoo** [lisen87/image_pickers#109]
I can't build ios app after upgrade to last version 2.0.0+6 
Xcode gives me these errors

![Screen Shot 2023-02-25 at 11 29 33 AM](https://user-images.githubusercontent.com/13227239/221349818-f8278a14-c218-4556-a5bd-6c0d0b61f051.png)

If I downgrade to pervious version 2.0.0+2 these errors will gone.

**Comment by cooliooau** [comment]
I'm facing the same issue in iOS, how to downgrade to pervious version 2.0.0+2 in iOS?

**Comment by cuixiaocun** [comment]
1.delete  image_pickers pub get   
2.add image_pickers: ^2.0.0+6  pub get   
or 
try delete these 
![截屏2023-03-06 08 49 58](https://user-images.githubusercontent.com/16298306/222996751-a30b5da9-5389-43a5-b2f7-6c2f82d5b766.png)
and  pod install again

**Comment by norbertkross** [comment]
Why is this issue closed when there is no way to fix it yet?

**Comment by cuixiaocun** [comment]
> 为什么这个问题在没有办法修复的情况下被关闭？


You can upgrade to the latest version  2.0.0+9
已解决此问题
