### ISSUE TITLE
android 13适配问题

### ISSUE THREAD

**Issue by cs453146042** [lisen87/image_pickers#110]
您好开发者：
           使用andoroid 13时图片选择器  会报错“读取内存卡权限被拒绝”  还请适配修复  谢谢

**Comment by lisen87** [comment]
你好，急用请先暂时fork一下，自己修改一下，AndroidManifest.xml ，添加一下权限。
安卓使用的库是：https://github.com/LuckSiege/PictureSelector 。参照调整一下试试。

**Comment by lisen87** [comment]
简单办法：
Android 13版本适配，细化存储权限
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />

在你项目中的 AndroidManifest.xml 中 添加这几行试试。

**Comment by lisen87** [comment]
Android 13版本适配，细化存储权限

uses-permission android:name="android.permission.READ_MEDIA_IMAGES" 
uses-permission android:name="android.permission.READ_MEDIA_AUDIO" 
uses-permission android:name="android.permission.READ_MEDIA_VIDEO" 

简单办法：
Android 13版本适配，细化存储权限


在你项目中的 AndroidManifest.xml 中 添加这几行试试。

**Comment by cs453146042** [comment]
这些权限 目前在项目的xml文件中做了添加  但是进入到相册时会直接弹入到app设置页面  但是设置后依然无效···   如果方便是否可添加您的微信做进一步沟通

**Comment by lisen87** [comment]
先下载个apk试一试 https://github.com/LuckSiege/PictureSelector/tree/version_component/app/demo 。我这边没有13的手机 ..........。
如果 demo 也不行，那就只能等 PictureSelector  作者更新了。

 https://github.com/LuckSiege/PictureSelector/issues/2599。

**Comment by cs453146042** [comment]
使用了您提供的apk   选择了系统相册后  进入可展示系统相册的照片   我使用的测试机也是模拟器  还麻烦您有空的时候看看是否可修复此bug  辛苦您啦

**Comment by lisen87** [comment]
2.0.0+7刚发布，等会试试吧。

**Comment by cs453146042** [comment]
谢谢大佬的技术支持，请收下我的膝盖
