### ISSUE TITLE
图片裁剪能否支持缩放

### ISSUE THREAD

**Issue by Zvirtuey** [lisen87/image_pickers#112]
没有缩放有的裁剪出来还有白边
![image](https://user-images.githubusercontent.com/20436938/227756795-c4300ab6-8dfd-4fa9-8e55-702465450dd4.png)

**Comment by lisen87** [comment]
可以缩放的，双指缩放。模拟器的话试试ctrl，鼠标滚珠

**Comment by Zvirtuey** [comment]
ok
