### ISSUE TITLE
Unrestricted Aspect Ratio

### ISSUE THREAD

**Issue by zamirszn** [lisen87/image_pickers#118]
how do i implement cropping with any aspect ratio ?

**Comment by lisen87** [comment]
try  it  ----->   CropConfig(enableCrop: true, width: 99, height: 125)

**Comment by zamirszn** [comment]
> try  it  ----->   CropConfig(enableCrop: true, width: 99, height: 125)

okay thanks alot , I'll get back to you

**Comment by zamirszn** [comment]
> try  it  ----->   CropConfig(enableCrop: true, width: 99, height: 125)

![Screenshot_20230629-222702.png](https://github.com/lisen87/image_pickers/assets/31168776/671394be-b69a-463a-843f-bd5e4b1695f0)

is it possible to implement the crop like this

**Comment by lisen87** [comment]
Currently, this function is not implemented。This function may be added in the future

**Comment by zamirszn** [comment]
> Currently, this function is not implemented。This function may be added in the future

okay thanks

**Comment by zamirszn** [comment]
> Currently, this function is not implemented。This function may be added in the future

hey hi, do you by any chance know how i can implement this please?

**Comment by lisen87** [comment]
[@zamirszn](https://github.com/lisen87/image_pickers/issues/118#issuecomment-1613832081)

Plugin updated 。image_pickers:  2.0.4+2。
You can give it a try。
`CropConfig(enableCrop: true,width: -1, height: -1) or CropConfig(enableCrop: true).`

**Comment by zamirszn** [comment]
>  [@zamirszn](https://github.com/lisen87/image_pickers/issues/118#issuecomment-1613832081)
> 
> Plugin updated 。image_pickers:  2.0.4+2。
> You can give it a try。
> `CropConfig(enableCrop: true,width: -1, height: -1) or CropConfig(enableCrop: true).`

Waw , thanks alot , I appreciate
