### ISSUE TITLE
There is an issue with aligning when selecting multiple images.

### ISSUE THREAD

**Issue by limdp99** [lisen87/image_pickers#126]
Device: iPhone 11 Pro
image_pickers: ^2.0.4+5

When selecting multiple images, the numbers on top of the thumbnails are aligning to the left, not the center.

![IMG_2044](https://github.com/lisen87/image_pickers/assets/47866457/885f9984-15be-462d-88ae-42722cbc3dcb)

**Comment by cuixiaocun** [comment]
已更新
