### ISSUE TITLE
Semantic Issue (Xcode): Property 'timeout' not found on object of type 'ZLPhotoConfiguration *' /Users/anmolgupta/.pub-cache/hosted/pub.dev/image_pickers-2.0.4+6/ios/Classes/ImagePickersPlugin.m:181:22

### ISSUE THREAD

**Issue by anmolgupta321** [lisen87/image_pickers#129]

**Comment by q200892907** [comment]
> 检查一下dart packages 下的image_picker 是不是2.0.4+6 如果不是将 image_pickers: ^2.0.4+6改为 image_pickers: 2.0.4+6 固定版本 然后 重新pub get 然后 删掉 Podfile.lock 重新pod install

最新的ZLPhotoConfiguration中没有timeout配置了

**Comment by q200892907** [comment]
> how can i update the version of ZLPhotoBrowser
作者已经更新了，2.0.4+7

**Comment by cuixiaocun** [comment]
已更新
