### ISSUE TITLE
App closes automatically after selecting multiple images.

### ISSUE THREAD

**Issue by 91priyansh** [lisen87/image_pickers#13]
Here is my code.

  void pickImages() async{
    List<Media> images;
    try {
    images = await ImagePickers.pickerPaths(
        selectCount: 3,
        compressSize: 500,
        cropConfig: CropConfig(
          enableCrop: true,
          width: 2,
          height: 1
        ),
        showCamera: false,
        galleryMode: GalleryMode.image,
        uiConfig: UIConfig(
          uiThemeColor: Colors.white,
        ),
      );

    }on PlatformException catch(e){
      print(e.toString());
    }
    
    images.forEach((image){
      print(image.path);
    });
  }

**Comment by lisen87** [comment]
don't set cropConfig
