### ISSUE TITLE
Glide 报错。

### ISSUE THREAD

**Issue by sm9i** [lisen87/image_pickers#14]
`
/Users/renzhayi/SDK/FlutterSDK/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/image_pickers-1.0.5+3/android/src/main/java/com/leeson/image_pickers/utils/GlideEngine.java:26: 错误: 无法访问Fragment
        Glide.with(context).load(url).into(imageView);
             ^
  找不到android.support.v4.app.Fragment的类文件
/Users/renzhayi/SDK/FlutterSDK/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub%47/image_pickers-1.0.5+3/android/src/main/java/com/leeson/image_pickers/utils/GlideEngine.java:32: 错误: 无法访问FragmentActivity
        Glide.with(context)
             ^
  找不到android.support.v4.app.FragmentActivity的类文件
` 

我试了试 使用
https://github.com/lisen87/image_pickers/issues/5 
的解决方案，但是无效

**Comment by sm9i** [comment]
这是android 目录单独 编译的 error 
`错误: 无法访问FragmentActivity
找不到android.support.v4.app.FragmentActivity的类文件
`

**Comment by lisen87** [comment]
>试试最新版本的1.0.7+1,你的问题可能是缓存问题

**Comment by sm9i** [comment]
试过了。。还是无法访问Fragment
