### ISSUE TITLE
iOS release crash

### ISSUE THREAD

**Issue by harloom** [lisen87/image_pickers#16]
error: Unexpected duplicate tasks:
               1) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/left_arrow.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow.png'
               2) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/left_arrow.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow.png'
           
               Build system information
               error: Unexpected duplicate tasks:
               1) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/error.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/error.png'
               2) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/error.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/error.png'
           
               Build system information
               error: Unexpected duplicate tasks:
               1) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/left_arrow@2x.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow@2x.png'
               2) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/left_arrow@2x.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/left_arrow@2x.png'
           
               Build system information
               error: Unexpected duplicate tasks:
               1) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/right_arrow@2x.png' to

'/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow@2x.png'
               2) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/right_arrow@2x.png' to

'/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow@2x.png'
           
               Build system information
               error: Unexpected duplicate tasks:
               1) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/right_arrow.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow.png'
               2) Target 'image_pickers' (project 'Pods') has copy command from
               '/Users/shiro/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.7+1/ios/Classes/AKGallery/img/right_arrow.png' to
               '/Users/shiro/Documents/Projectsflu/build/ios/Release-iphoneos/image_pickers/image_pickers.framework/right_arrow.png'

**Comment by lisen87** [comment]
https://github.com/lisen87/image_pickers/issues/10
maybe can help you
