### ISSUE TITLE
安卓SDK版本太低

### ISSUE THREAD

**Issue by Dorbmon** [lisen87/image_pickers#17]
uses-sdk:minSdkVersion 16 cannot be smaller than version 17 declared in library [:image_pickers] /my_flutter/build/image_pickers/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16

**Comment by oreo** [comment]
我也遇到这个问题，Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:image_pickers]

**Comment by Dorbmon** [comment]
> 我也遇到这个问题，Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:image_pickers]

别用这个插件了。。。一个issue都没回

**Comment by lisen87** [comment]
@Dorbmon  别胡说，你去看看有没有回复的。

**Comment by lisen87** [comment]
@oreo 打开你的安卓项目，同步成功后，修改build.gradle文件中，minSdkVersion 16 改为 minSdkVersion 19 同步就好了

**Comment by Dorbmon** [comment]
> @Dorbmon 别胡说，你去看看有没有回复的。

7 Feb 提的。。为啥我一说没人回复就回复。神奇>_<

**Comment by lisen87** [comment]
这是安卓基础的，以为都会的，百度一下基本能找到原因的

**Comment by cuixiaocun** [comment]
wait a moment，I will update a new version




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dorbmon"<notifications@github.com&gt;; 
发送时间: 2020年6月15日(星期一) 上午10:32
收件人: "lisen87/image_pickers"<image_pickers@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [lisen87/image_pickers] 安卓SDK版本太低 (#17)





 
Closed #17.
