### ISSUE TITLE
选择iCloud上视频，会崩溃

### ISSUE THREAD

**Issue by saxon134** [lisen87/image_pickers#18]
视频存储在iCloud上，尚未下载到相册。选择图片会出现‘‘处理中‘’的字样，之后就崩溃了。
同样情况下，如果是图片，则是正常的

Error msg:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

**Comment by saxon134** [comment]
补充一下，视频如果已经下载到相册，选择视频是正常的。

**Comment by DuQuanzhong** [comment]
我也遇到了同样的问题  就是iOS中的iCloud视频选择会闪退

**Comment by cuixiaocun** [comment]
已更新
