### ISSUE TITLE
这个问题怎么解决啊 app:transformClassesWithMultidexlistForDebug

### ISSUE THREAD

**Issue by QTTQ** [lisen87/image_pickers#2]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

查 gradlew  assembleDebug  --stacktrace 的结果

> Configure project :barcode_scan
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :barcode_scan:compileDebugKotlin FAILED
248 actionable tasks: 10 executed, 238 up-to-date
         *********************************************************
WARNING: This version of device_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':barcode_scan:compileDebugKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'D:\java' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':barcode_scan:compileDebugKotlin'.
。。。

**Comment by LiWangWu** [comment]
解决了吗?😁
