### ISSUE TITLE
IOS enableCrop false无效

### ISSUE THREAD

**Issue by fcloud89** [lisen87/image_pickers#39]
ios 13.6

**Comment by fcloud89** [comment]
@lisen87 @cuixiaocun

**Comment by yanivshaked** [comment]
I believe my pull request solves this issue, please try it. Edit your pubspec.yaml file:

  image_pickers:
    git:
      url: https://github.com/yanivshaked/image_pickers.git
      ref: 20200812_iosNoCrop

Please let me know if it works for you!

**Comment by zhouxting** [comment]
请问这个解决了吗

**Comment by lisen87** [comment]
> ios 13.6

1.0.8+2版本已修复

**Comment by lisen87** [comment]
> 请问这个解决了吗

1.0.8+2版本已修复
