### ISSUE TITLE
ios版本选择图片后，没有确定按钮，安卓是可以正常使用的

### ISSUE THREAD

**Issue by eyeshot** [lisen87/image_pickers#48]
ios版本打开选择图片框后，里面没有确认按钮，选择图片后不能确定返回，界面上只有 “返回” 和 “取消” 按钮，机型是 iphone8 Plus.

**Comment by cuixiaocun** [comment]
你是暗黑模式底下运行的吗？或者是你设置的按钮颜色和主题颜色是否重复？

**Comment by cuixiaocun** [comment]
你是暗黑模式底下运行的吗？或者是你设置的按钮颜色和主题颜色和字体颜色重复？

**Comment by cuixiaocun** [comment]
最新版本可用
