### ISSUE TITLE
package com.bumptech.glide.request.target does not exist

### ISSUE THREAD

**Issue by mtellect** [lisen87/image_pickers#5]
Hello, i get this error when trying to run ver  image_pickers: ^1.0.5+2 on Android... doesnt pass the build stage just returns the error on the android side

Note: /Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_list-0.1.3+2/android/src/main/java/com/ric/image_list/ImageList.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/PhotosActivity.java:17: error: cannot find symbol
import com.bumptech.glide.Glide;
                         ^
  symbol:   class Glide
  location: package com.bumptech.glide
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/PhotosActivity.java:18: error: package com.bumptech.glide.request.target does not exist
import com.bumptech.glide.request.target.SimpleTarget;
                                        ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/PhotosActivity.java:19: error: package com.bumptech.glide.request.transition does not exist
import com.bumptech.glide.request.transition.Transition;
                                            ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/VideoActivity.java:21: error: cannot find symbol
import com.bumptech.glide.Glide;
                         ^
  symbol:   class Glide
  location: package com.bumptech.glide
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:11: error: cannot find symbol
import com.bumptech.glide.Glide;
                         ^
  symbol:   class Glide
  location: package com.bumptech.glide
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:12: error: package com.bumptech.glide.load does not exist
import com.bumptech.glide.load.DataSource;
                              ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:13: error: package com.bumptech.glide.load.engine does not exist
import com.bumptech.glide.load.engine.GlideException;
                                     ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:14: error: package com.bumptech.glide.request does not exist
import com.bumptech.glide.request.RequestListener;
                                 ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:15: error: package com.bumptech.glide.request.target does not exist
import com.bumptech.glide.request.target.SimpleTarget;
                                        ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:16: error: package com.bumptech.glide.request.target does not exist
import com.bumptech.glide.request.target.Target;
                                        ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:17: error: package com.bumptech.glide.request.transition does not exist
import com.bumptech.glide.request.transition.Transition;
                                            ^
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/PhotosActivity.java:93: error: cannot find symbol
                Glide.with(PhotosActivity.this).load(url).into(new SimpleTarget<Drawable>() {
                                                                   ^
  symbol:   class SimpleTarget
  location: class PhotosActivity.Adapter
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/PhotosActivity.java:93: error: cannot find symbol
                Glide.with(PhotosActivity.this).load(url).into(new SimpleTarget<Drawable>() {
                ^
  symbol:   variable Glide
  location: class PhotosActivity.Adapter
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/VideoActivity.java:82: error: cannot find symbol
                    Glide.with(this).asBitmap().load(thumbPath).into(iv_src);
                    ^
  symbol:   variable Glide
  location: class VideoActivity
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:66: error: cannot find symbol
                }).into(new SimpleTarget<Bitmap>() {
                            ^
  symbol:   class SimpleTarget
  location: class SaveImageToGalleryActivity
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:53: error: cannot find symbol
                Glide.with(this).asBitmap().load(imageUrl).listener(new RequestListener<Bitmap>() {
                                                                        ^
  symbol:   class RequestListener
  location: class SaveImageToGalleryActivity
/Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/activitys/SaveImageToGalleryActivity.java:53: error: cannot find symbol
                Glide.with(this).asBitmap().load(imageUrl).listener(new RequestListener<Bitmap>() {
                ^
  symbol:   variable Glide
  location: class SaveImageToGalleryActivity
Note: /Users/bappstack/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.5+2/android/src/main/java/com/leeson/image_pickers/ImagePickersPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
17 errors
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by lisen87** [comment]
Hello, I have dealt with this problem. Try using version 1.0.5+3. If you have any problems, please point out

**Comment by mtellect** [comment]
Yes...works perfectly now.... you did a great job
