### ISSUE TITLE
Xcode : 'ZLPhotoBrowser-objc/ZlPhotoActionSheet.h' file not found

### ISSUE THREAD

**Issue by maplechen52** [lisen87/image_pickers#51]
# import <ZLPhotoBrowser-objc/ZlPhotoActionSheet.h> --> file not fond
# import <ZLPhotoBrowser_objc/ZlPhotoActionSheet.h> --> 才可以…

**Comment by zeusbaba** [comment]
I have the same issue... it broke my build after upgrading to `image_pickers: ^1.0.8+3`  

```
...
image_pickers-1.0.8+3/ios/Classes/BigImageViewController.h:10:9:
    fatal error: 'ZLPhotoBrowser-objc/ZLPhotoActionSheet.h' file not found
    #import <ZLPhotoBrowser-objc/ZLPhotoActionSheet.h>

```  

please help/fix

**Comment by lisen87** [comment]
新版本已处理

**Comment by zeusbaba** [comment]
thanks for the fix
