### ISSUE TITLE
ios拍照无后缀，选择相册后缀为.(null)

### ISSUE THREAD

**Issue by fcloud89** [lisen87/image_pickers#55]
拍照返回
"/var/mobile/Containers/Data/Application/EE90461F-9BAF-4CF7-9839-A00F1CA1F936/Documents/20201021161536013994"
选择相册返回会有2种情况，似乎被存到icloud的图片选择后会出现null后缀，本地刚拍摄的图片，在相册选中则正常？
/var/mobile/Containers/Data/Application/EE90461F-9BAF-4CF7-9839-A00F1CA1F936/Documents/2020102116162101202010211616202416427.jpeg
/var/mobile/Containers/Data/Application/EE90461F-9BAF-4CF7-9839-A00F1CA1F936/Documents/2020102116173101202010211617310.(null)
@cuixiaocun @lisen87

**Comment by cuixiaocun** [comment]
已更新
