### ISSUE TITLE
'ZLPhotoBrowser/ZLPhotoBrowser-Swift.h' file not found 

### ISSUE THREAD

**Issue by chenyifan88** [lisen87/image_pickers#58]
/Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.8+5/ios/Classes/ImagePickersPlugin.m:3:9: fatal error: 'ZLPhotoBrowser/ZLPhotoBrowser-Swift.h' file not found
#import <ZLPhotoBrowser/ZLPhotoBrowser-Swift.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mac/development/flutter/.pub-cache/hosted/pub.dartlang.org/image_pickers-1.0.8+5/ios/Classes/ImagePickersPlugin.m:3:9: note: did not find header 'ZLPhotoBrowser-Swift.h' in framework 'ZLPhotoBrowser' (loaded from '/Users/mac/Library/Developer/Xcode/DerivedData/Runner-hiesxxgwtyktreelctuzogmachvf/Build/Products/Debug-iphonesimulator/ZLPhotoBrowser')
1 error generated.

Xcode 12

**Comment by lisen87** [comment]
新版本尝试修复这个问题了

**Comment by cuixiaocun** [comment]
升级最新版本
