### ISSUE TITLE
Option for more flexibility in cropping

### ISSUE THREAD

**Issue by mtellect** [lisen87/image_pickers#6]
Can there be more flexibility in cropping? to support flexible crop ratios?
just like :

  Circle cropping
  Square cropping,
  Rectangular cropping
  CropAspectRatioPreset.ratio3x2,
  CropAspectRatioPreset.ratio4x3,
  CropAspectRatioPreset.ratio16x9

then when you try to use external crop tool like image_cropper: ^1.1.0, doesnt work together with it because the media.path or media.thumbPath returns something like this 

```
/Users/bappstack/Library/Developer/CoreSimulator/Devices/F30C7246-0484-4E7B-BBEB-E2711F360C6E/data/Containers/Data/Application/298C6216-EE71-4988-AD2C-53135CFA32BE/Documents/2019112621390301(null)
```
which i dont think is a complete file path

**Comment by lisen87** [comment]
corpConfig: CorpConfig(enableCrop: true, width: 2, height: 1));Any scale is supported, circle clipping is not supported temporarily
