### ISSUE TITLE
iOS ZLPhotoBrowser 版本

### ISSUE THREAD

**Issue by peakerWu** [lisen87/image_pickers#61]
ZLPhotoBrowser的swift版本已经更新适配了iOS14，选择图片时，有个这个功能
![image](https://user-images.githubusercontent.com/16396005/98665793-184a1f00-2387-11eb-8002-704e03741f73.png)，但是ZLPhotoBrowser-objc 好像没有这个功能，这个库好像也不维护了。不知道能否转换到 swift版本的？

**Comment by cuixiaocun** [comment]
这个应该是没开启权限问题
