### ISSUE TITLE
android 拍摄的视频丢失

### ISSUE THREAD

**Issue by tianfachina** [lisen87/image_pickers#64]
视频拍摄页面   拍摄和视频选择共存的情况

点击相机拍摄视频，选中列表中的视频，点击完成，首页可以正常展示选择的视频

再次进入拍摄和视频选择共存页面，发现视频列表中没有前一次拍摄的视频。

多次操作发现每次进入列表页，都不显示前一次拍摄的视频

**Comment by lisen87** [comment]
点击相机拍摄视频 并不会存储到 系统视频中，
