### ISSUE TITLE
ios 引入该包后无法构建app

### ISSUE THREAD

**Issue by sunjianan9900** [lisen87/image_pickers#65]
flutter 版本： Flutter (Channel dev, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans-CN)

错误信息：

Xcode's output:
↳
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/DKPhotoGallery/DKPhotoGallery/Preview/ImagePreview/DKPhotoBaseImagePreviewVC.swift:11:8: error: compiling for iOS 9.0, but module 'SwiftyGif' has a minimum deployment target of iOS 10.0: /Users/mymac/Documents/myProject/2020pro/11/myapp2021/build/ios/Debug-iphonesimulator/SwiftyGif/SwiftyGif.framework/Modules/SwiftyGif.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    import SwiftyGif
           ^
    In file included from /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLVideoPlayerControl.m:10:
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLDefine.h:242:21: warning: 'imageNamed:inBundle:withConfiguration:' is only available on iOS 13.0 or newer [-Wunguarded-availability-new]
        return [UIImage imageNamed:name inBundle:NSBundle.zlPhotoBrowserBundle withConfiguration:nil];
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/Target Support Files/ZLPhotoBrowser-objc/ZLPhotoBrowser-objc-prefix.pch:2:
    /Volumes/mymac/APP/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:91:1: note: 'imageNamed:inBundle:withConfiguration:' has been marked as being introduced in iOS 13.0 here, but the deployment target is iOS 10.0.0
    + (nullable UIImage *)imageNamed:(NSString *)name inBundle:(nullable NSBundle *)bundle withConfiguration:(nullable UIImageConfiguration *)configuration API_AVAILABLE(ios(13.0),tvos(13.0),watchos(6.0));
    ^
    In file included from /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLVideoPlayerControl.m:10:
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLDefine.h:242:21: note: enclose 'imageNamed:inBundle:withConfiguration:' in an @available check to silence this warning
        return [UIImage imageNamed:name inBundle:NSBundle.zlPhotoBrowserBundle withConfiguration:nil];
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    In file included from /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLProgressHUD.m:10:
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLDefine.h:242:21: warning: 'imageNamed:inBundle:withConfiguration:' is only available on iOS 13.0 or newer [-Wunguarded-availability-new]
        return [UIImage imageNamed:name inBundle:NSBundle.zlPhotoBrowserBundle withConfiguration:nil];
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'UIKit' imported from /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/Target Support Files/ZLPhotoBrowser-objc/ZLPhotoBrowser-objc-prefix.pch:2:
    /Volumes/mymac/APP/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIImage.h:91:1: note: 'imageNamed:inBundle:withConfiguration:' has been marked as being introduced in iOS 13.0 here, but the deployment target is iOS 10.0.0
    + (nullable UIImage *)imageNamed:(NSString *)name inBundle:(nullable NSBundle *)bundle withConfiguration:(nullable UIImageConfiguration *)configuration API_AVAILABLE(ios(13.0),tvos(13.0),watchos(6.0));
    ^
    In file included from /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLProgressHUD.m:10:
    /Users/mymac/Documents/myProject/2020pro/11/myapp2021/ios/Pods/ZLPhotoBrowser-objc/ZLPhotoBrowser/PhotoBrowser/ZLDefine.h:242:21: note: enclose 'imageNamed:inBundle:withConfiguration:' in an @available check to silence this warning
        return [UIImage imageNamed:name inBundle:NSBundle.zlPhotoBrowserBundle withConfiguration:nil];
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by sunjianan9900** [comment]
image_pickers 1.0.8+7 版本

**Comment by amiruljack** [comment]
same
