### ISSUE TITLE
ios点击图片或者预览，图片无法显示，一片黑色的

### ISSUE THREAD

**Issue by ihongwu** [lisen87/image_pickers#68]
image_pickers: ^1.0.8+7

List<Media> _listImagePaths = await ImagePickers.pickerPaths(
    galleryMode: GalleryMode.image,
    selectCount: 2,
    showGif: false,
    showCamera: true,
    compressSize: 500,
    uiConfig: UIConfig(uiThemeColor: defaultColor),
    cropConfig: CropConfig(enableCrop: false, width: 2, height: 1)
);

![image](https://user-images.githubusercontent.com/21274377/104563432-99be7600-5684-11eb-9752-b7539f29a314.png)

点击图片或者预览后就黑屏了

![image](https://user-images.githubusercontent.com/21274377/104563477-a80c9200-5684-11eb-9e0f-201bb7896f7a.png)

**Comment by ihongwu** [comment]
iphone6s plus 和模拟器都有这个问题

**Comment by Keanyuan** [comment]
你解决了吗  我发现在iOS14以上都会有这样的问题

**Comment by Keanyuan** [comment]
升级SDWebImage
或者修改本地Pod  SDAnimatedImageView.m中
```
- (void)displayLayer:(CALayer *)layer
{
    if (_currentFrame) {
        layer.contentsScale = self.animatedImageScale;
        layer.contents = (__bridge id)_currentFrame.CGImage;
    }
}
```
为
```
UIImage *currentFrame = self.currentFrame;
if (currentFrame) {
    layer.contentsScale = currentFrame.scale;
    layer.contents = (__bridge id)currentFrame.CGImage;
} else {
    // If we have no animation frames, call super implementation. iOS 14+ UIImageView use this delegate method for rendering.
    if ([UIImageView instancesRespondToSelector:@selector(displayLayer:)]) {
        [super displayLayer:layer];
    }
}
```

**Comment by ihongwu** [comment]
谢谢，我已经不用这个插件啦
