### ISSUE TITLE
iOS Bug

### ISSUE THREAD

**Issue by malikdoksoz** [lisen87/image_pickers#7]
Flutter v1.12.13+hotfix.5

When I turn off cropping(**enableCrop: false**) when I select photo on gallery, it gives an error. 

> flutter: [Instance of 'Media']

════════ Exception caught by image resource service ════════════════════════════
Cannot open file, path = '/var/mobile/Containers/Data/Application/18550D3F-7FF6-4388-80E1-795555C706A2/Documents/2019121123570201(null)' (OS Error: No such file or directory, errno = 2)

**Comment by lisen87** [comment]
Bug fixed 1.0.6+2
