### ISSUE TITLE
iOS中需要将PHImageRequestOptions的networkAccessAllowed改为yes，否则打开iCloud的资源时会因为获取不到资源导致闪退

### ISSUE THREAD

**Issue by aiyouBug** [lisen87/image_pickers#80]

**Comment by aiyouBug** [comment]
在-(void)saveImageView:(NSInteger)index imagePHAsset:(NSArray*)assets arr:(NSMutableArray*)arr compressSize:(NSInteger)compressSize result:(FlutterResult)result中的PHImageRequestOptions *option =[[PHImageRequestOptions alloc]init];
后增加`option.networkAccessAllowed = YES;`

**Comment by cuixiaocun** [comment]
已增加
