### ISSUE TITLE
Please migrate to null-safety version!🙏

### ISSUE THREAD

**Issue by RA1NO3O** [lisen87/image_pickers#82]
Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:
- package:image_pickers
    For solutions, see https://dart.dev/go/unsound-null-safety

**Comment by azhansy** [comment]
Thank you very much, this is a very good warehouse, I hope to support empty safety, whether there is time to schedule to deal with

**Comment by lisen87** [comment]
2.0.0 support null safety
