### ISSUE TITLE
iOS 13 以下设备使用崩溃，跟 ZLPhotoBrowser 有关

### ISSUE THREAD

**Issue by ZhengXiaoMing** [lisen87/image_pickers#84]
ZLPhotoBrowser 1.0.2之前版本 GetImageWithName 方法中使用了一个 iOS 13 以上才可用的 API，导致 iOS 13 以下设备崩溃，ZLPhotoBrowser 作者在 1.0.3版本修正了这个 bug，image_pickers 的 podspec 文件引用的还是 1.0.2 版本，建议作者升级。

**Comment by cuixiaocun** [comment]
已升级
