### ISSUE TITLE
相册图片显示不出来

### ISSUE THREAD

**Issue by weiwei00200** [lisen87/image_pickers#93]
![1632878140(1)](https://user-images.githubusercontent.com/6120637/135186449-11da01ab-9e49-4a13-8f95-4ecb10944edf.png)
荣耀9X，Android10
Flutter SDK 2.2.3
上面环境下打开相册选择图片的时候一直loading。手头另一个手机正常。

**Comment by quanzhang11** [comment]
我也一样
