### ISSUE TITLE
关于Android http兼容的文件冲突问题。

### ISSUE THREAD

**Issue by ymwm-lxl** [lisen87/image_pickers#98]
开发者您好，首先感谢您通过自己高超的技艺制作并且发布了该开源插件库，造福广大秃头佬。

我使用的是 1.1.0版本的imagepickers（因为我这边没有升级更高版本的 Flutter 运行环境）。导入之后运行 Android 侧的时候我们日夜相伴的 IDE-Android Studio 爆出了一个红色异常，含义是我们导入的在高版本Android 上面兼容陈旧的 Http 请求的 xml 文件与您的清单文件中的设置发生了令人不悦的冲突。所以恳求开发者能够在发布版本删掉 android:networkSecurityConfig="@xml/net_sec" 这一句，避免其他与我类似的开发者遭遇到这样使人痛苦的问题。

再次为您的贡献表达感谢，也希望您能够百忙之中抽出时间来进行修改。

**Comment by lisen87** [comment]
可以fork一下，回滚到指定版本，使用你自己的github版本。或者修改一下你本地当前插件的源码临时使用

**Comment by lisen87** [comment]
可以fork一下，回滚到指定版本，使用你自己的github版本。或者修改一下你本地当前插件的源码临时使用
